apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fcg-user-api.fullname" . }}-secrets
  labels: {{- include "fcg-user-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  connectionString: "{{ .Values.secrets.connectionString }}"
  jwt-issuer: "{{ .Values.secrets.jwt.issuer }}"
  jwt-audience: "{{ .Values.secrets.jwt.audience }}"
  jwt-key: "{{ .Values.secrets.jwt.key }}"
