apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "fcg-user-api.fullname" . }}-externalsecret
  namespace: {{ .Release.Namespace }}
  labels: {{- include "fcg-user-api.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "fcg-user-api.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: {{ include "fcg-user-api.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: connectionString
      remoteRef:
        key: fcg-api-user-connection-string
    - secretKey: jwt-issuer
      remoteRef:
        key: fcg-jwt-config
        property: issuer
    - secretKey: jwt-audience
      remoteRef:
        key: fcg-jwt-config
        property: audience
    - secretKey: jwt-key
      remoteRef:
        key: fcg-jwt-config
        property: key
